### ISSUE TITLE
Detect unused domains

### ISSUE THREAD

**Issue by Foxboron** [byeskille/norway-gov-domains#3]
I know there are a few domains that is not used and points too a 404 page. An idea is too maybe go through these pages and filter them out?

**Comment by byeskille** [comment]
This list is not intended to show active sites, but domains owned by the Norwegian government.
It is used for scans like this [HTTPS-Norge på NRKbeta](https://nrkbeta.no/https-norge/) and the usage of the domains change. So filtering out every domain that at some point gave a 404 might not be a good solution.
If there is need for a list of active sites a fork of this list with such a filter might be an idea.
